name = "openai-workers-proxy"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production.vars]
# 在 Cloudflare Workers Dashboard 中设置环境变量
# OPENAI_API_KEY = "your-openai-api-key-here"

[env.development.vars]
# 开发环境变量
# OPENAI_API_KEY = "your-development-openai-api-key-here"
